export enum FunctionType {
  And = 'And',
  Average = 'Average',
  Calculator = 'Calculator',
  Calendar = 'Calendar',
  Clamp = 'Clamp',
  Comparator = 'Comparator',
  Delay = 'Delay',
  If = 'If',
  Invert = 'Invert',
  Line = 'Line',
  Max = 'Max',
  Min = 'Min',
  Or = 'Or',
  Override = 'Override',
  Pid = 'Pid',
  Pulse = 'Pulse',
  Schedule = 'Schedule',
  Selector = 'Selector',
  Sequence = 'Sequence',
  Split = 'Split',
  Timer = 'Timer',
  Xnor = 'Xnor',
  Xor = 'Xor'
}
